/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package automation.of.office.work;

public class App {

    public static void main(String[] args) {
        System.out.println("hello world!!!");
    }
}
