/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pure.java;

import java.util.Date;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        String ddd = String.format("%-6s", "aa");
        System.out.println(ddd);
        System.out.println(ddd.length());

        System.out.println(new Date(-1));
        System.out.println(new Date(-1000));
    }
}
