/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pure.java;

import java.util.Comparator;
import java.util.List;
import java.util.Locale;
import java.util.Random;
import java.util.stream.Stream;

import com.github.javafaker.Faker;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
		Faker faker = new Faker(Locale.getDefault());
		Random random = new Random();
		int AGE_MAX = 60;
		int LIST_NODE_MAX = random.nextInt(100);

		Comparator<Person> comparator = Comparator.comparing(Person::getMonth).thenComparing(Person::getAge);

        List<Person> list =  Stream.generate(() -> new Person(faker.name().fullName(), random.nextInt(AGE_MAX), random.nextInt(12) + 1))
			.limit(LIST_NODE_MAX).toList();

		System.out.println(list);

		list = list.stream().sorted(comparator).toList();

		System.out.println(list);
    }

	@Data
	@AllArgsConstructor
	@NoArgsConstructor
	static class Person{
		private String name;
		private int age;
		private int month;
	}
}
